### ISSUE TITLE
Redfish: 500 error on GET /redfish/v1/UpdateService

### ISSUE THREAD

**Issue by leiyu-bytedance** [Intel-BMC/openbmc#45]
**Note on Bugs**
The BMC gives 500 error on `GET /redfish/v1/UpdateService`

**Expected behavior**
The redfish `GET /redfish/v1/UpdateService` should give 200 OK.

**To Reproduce**
```
$ curl -k -H "X-Auth-Token: $token" https://${bmc}/redfish/v1/UpdateService
{
  "@odata.id": "/redfish/v1/UpdateService",
  "@odata.type": "#UpdateService.v1_4_0.UpdateService",
  "Description": "Service for Software Update",
  "FirmwareInventory": {
    "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory"
  },
  "HttpPushUri": "/redfish/v1/UpdateService",
  "HttpPushUriOptions": {
    "HttpPushUriApplyTime": {
      "ApplyTime": "Immediate"
    }
  },
  "HttpPushUriTargets": [],
  "HttpPushUriTargetsBusy": false,
  "Id": "UpdateService",
  "Name": "Update Service",
  "ServiceEnabled": true,
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "#Message.v1_0_0.Message",
        "Message": "The request failed due to an internal service error.  The service is still operational.",
        "MessageArgs": [],
        "MessageId": "Base.1.4.0.InternalError",
        "Resolution": "Resubmit the request.  If the problem persists, consider resetting the service.",
        "Severity": "Critical"
      }
    ],
    "code": "Base.1.4.0.InternalError",
    "message": "The request failed due to an internal service error.  The service is still operational."
  }
}
```

**OpenBMC Information:**

The `intel` branch on 2a11ae52f

**Additional context**

The root cause is that `bmcweb` is querying the property `ClearConfig` in `xyz.openbmc_project.Software.ApplyOptions` interface, which is not enabled in phosphor-bmc-code-mgmt.

The patch `0009-Add-ApplyOptions-D-bus-property-under-Software.patch` is enabled only for `intel-pfr`:
```
$ cat meta-openbmc-mods/meta-common/recipes-phosphor/flash/phosphor-software-manager_%.bbappend
...
SRC_URI_PFR = "file://0007-PFR-images-support.patch \
               file://0008-PFR-image-HASH-verification.patch \
               file://0009-Add-ApplyOptions-D-bus-property-under-Software.patch \
              "

SRC_URI += "${@bb.utils.contains('IMAGE_FSTYPES', 'intel-pfr', SRC_URI_PFR, '', d)}"
```

**Comment by cjia4** [comment]
Could you provide the content of "cat /etc/os-release" under BMC console?

**Comment by leiyu-bytedance** [comment]
My build has downstream commits, so the `/etc/os-release` does not make sense here.
But the code base is 2a11ae5, which is the latest revision as of today (2020.07.27)

**Comment by cjia4** [comment]
{
    "@odata.id": "/redfish/v1/UpdateService",
    "@odata.type": "#UpdateService.v1_4_0.UpdateService",
    "Description": "Service for Software Update",
    "FirmwareInventory": {
        "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory"
    },
    "HttpPushUri": "/redfish/v1/UpdateService",
    "HttpPushUriOptions": {
        "HttpPushUriApplyTime": {
            "ApplyTime": "Immediate"
        }
    },
    "HttpPushUriTargets": [],
    "HttpPushUriTargetsBusy": false,
    "Id": "UpdateService",
    "Name": "Update Service",
    "Oem": {
        "ApplyOptions": {
            "ClearConfig": false
        }
    },
    "ServiceEnabled": true
}







{
    "@odata.id": "/redfish/v1/Managers/bmc",
    "@odata.type": "#Manager.v1_9_0.Manager",
    "Actions": {
        "#Manager.Reset": {
            "@Redfish.ActionInfo": "/redfish/v1/Managers/bmc/ResetActionInfo",
            "target": "/redfish/v1/Managers/bmc/Actions/Manager.Reset"
        },
        "#Manager.ResetToDefaults": {
            "ResetType@Redfish.AllowableValues": [
                "ResetAll"
            ],
            "target": "/redfish/v1/Managers/bmc/Actions/Manager.ResetToDefaults"
        }
    },
    "DateTime": "2020-07-27T16:56:34+00:00",
    "Description": "Baseboard Management Controller",
    "EthernetInterfaces": {
        "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces"
    },
    "FirmwareVersion": "wht-0.73-0-g7cfc76-31e5d79",
    "GraphicalConsole": {
        "ConnectTypesSupported": [
            "KVMIP"
        ],
        "MaxConcurrentSessions": 4,
        "ServiceEnabled": true
    },
    "Id": "bmc",
    "LastResetTime": "2020-07-27T16:49:11+00:00",
    "Links": {
        "ManagerForChassis": [
            {
                "@odata.id": "/redfish/v1/Chassis/Intel_Front_Panel"
            }
        ],
        "ManagerForChassis@odata.count": 1,
        "ManagerForServers": [
            {
                "@odata.id": "/redfish/v1/Systems/system"
            }
        ],
        "ManagerForServers@odata.count": 1,
        "ManagerInChassis": {
            "@odata.id": "/redfish/v1/Chassis/Intel_Front_Panel"
        }
    },
    "LogServices": {
        "@odata.id": "/redfish/v1/Managers/bmc/LogServices"
    },
    "ManagerType": "BMC",
    "Model": "OpenBmc",
    "Name": "OpenBmc Manager",
    "NetworkProtocol": {
        "@odata.id": "/redfish/v1/Managers/bmc/NetworkProtocol"
    },
    "Oem": {
        "@odata.id": "/redfish/v1/Managers/bmc#/Oem",
        "@odata.type": "#OemManager.Oem",
        "OpenBmc": {
            "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc",
            "@odata.type": "#OemManager.OpenBmc",
            "Certificates": {
                "@odata.id": "/redfish/v1/Managers/bmc/Truststore/Certificates"
            },
            "Fan": {
                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan",
                "@odata.type": "#OemManager.Fan",
                "FanControllers": {
                    "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanControllers",
                    "@odata.type": "#OemManager.FanControllers",
                    "Fan_1": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanControllers/Fan_1",
                        "@odata.type": "#OemManager.FanController",
                        "FFGainCoefficient": 1,
                        "FFOffCoefficient": 0,
                        "ICoefficient": 0,
                        "ILimitMax": 0,
                        "ILimitMin": 0,
                        "Inputs": [
                            "Fan 1"
                        ],
                        "NegativeHysteresis": 0,
                        "OutLimitMax": 100,
                        "OutLimitMin": 0,
                        "Outputs": [
                            "Pwm 1"
                        ],
                        "PCoefficient": 0,
                        "PositiveHysteresis": 0,
                        "SlewNeg": 0,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Left"
                            }
                        ]
                    },
                    "Fan_2": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanControllers/Fan_2",
                        "@odata.type": "#OemManager.FanController",
                        "FFGainCoefficient": 1,
                        "FFOffCoefficient": 0,
                        "ICoefficient": 0,
                        "ILimitMax": 0,
                        "ILimitMin": 0,
                        "Inputs": [
                            "Fan 2"
                        ],
                        "NegativeHysteresis": 0,
                        "OutLimitMax": 100,
                        "OutLimitMin": 0,
                        "Outputs": [
                            "Pwm 2"
                        ],
                        "PCoefficient": 0,
                        "PositiveHysteresis": 0,
                        "SlewNeg": 0,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Left"
                            }
                        ]
                    },
                    "Fan_3": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanControllers/Fan_3",
                        "@odata.type": "#OemManager.FanController",
                        "FFGainCoefficient": 1,
                        "FFOffCoefficient": 0,
                        "ICoefficient": 0,
                        "ILimitMax": 0,
                        "ILimitMin": 0,
                        "Inputs": [
                            "Fan 3"
                        ],
                        "NegativeHysteresis": 0,
                        "OutLimitMax": 100,
                        "OutLimitMin": 0,
                        "Outputs": [
                            "Pwm 3"
                        ],
                        "PCoefficient": 0,
                        "PositiveHysteresis": 0,
                        "SlewNeg": 0,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Left"
                            }
                        ]
                    },
                    "Fan_4": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanControllers/Fan_4",
                        "@odata.type": "#OemManager.FanController",
                        "FFGainCoefficient": 1,
                        "FFOffCoefficient": 0,
                        "ICoefficient": 0,
                        "ILimitMax": 0,
                        "ILimitMin": 0,
                        "Inputs": [
                            "Fan 4"
                        ],
                        "NegativeHysteresis": 0,
                        "OutLimitMax": 100,
                        "OutLimitMin": 0,
                        "Outputs": [
                            "Pwm 6"
                        ],
                        "PCoefficient": 0,
                        "PositiveHysteresis": 0,
                        "SlewNeg": 0,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Right"
                            }
                        ]
                    },
                    "Fan_5": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanControllers/Fan_5",
                        "@odata.type": "#OemManager.FanController",
                        "FFGainCoefficient": 1,
                        "FFOffCoefficient": 0,
                        "ICoefficient": 0,
                        "ILimitMax": 0,
                        "ILimitMin": 0,
                        "Inputs": [
                            "Fan 5"
                        ],
                        "NegativeHysteresis": 0,
                        "OutLimitMax": 100,
                        "OutLimitMin": 0,
                        "Outputs": [
                            "Pwm 7"
                        ],
                        "PCoefficient": 0,
                        "PositiveHysteresis": 0,
                        "SlewNeg": 0,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Right"
                            }
                        ]
                    },
                    "Fan_6": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanControllers/Fan_6",
                        "@odata.type": "#OemManager.FanController",
                        "FFGainCoefficient": 1,
                        "FFOffCoefficient": 0,
                        "ICoefficient": 0,
                        "ILimitMax": 0,
                        "ILimitMin": 0,
                        "Inputs": [
                            "Fan 6"
                        ],
                        "NegativeHysteresis": 0,
                        "OutLimitMax": 100,
                        "OutLimitMin": 0,
                        "Outputs": [
                            "Pwm 8"
                        ],
                        "PCoefficient": 0,
                        "PositiveHysteresis": 0,
                        "SlewNeg": 0,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Right"
                            }
                        ]
                    },
                    "PSU1_Fan_1": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanControllers/PSU1_Fan_1",
                        "@odata.type": "#OemManager.FanController",
                        "FFGainCoefficient": 1,
                        "FFOffCoefficient": 0,
                        "ICoefficient": 0,
                        "ILimitMax": 0,
                        "ILimitMin": 0,
                        "Inputs": [
                            "PSU1 Fan Speed 1"
                        ],
                        "NegativeHysteresis": 2,
                        "OutLimitMax": 100,
                        "OutLimitMin": 0,
                        "Outputs": [
                            "Pwm PSU1 Fan 1"
                        ],
                        "PCoefficient": 0,
                        "PositiveHysteresis": 0,
                        "SlewNeg": 0,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/PSU"
                            }
                        ]
                    },
                    "PSU1_Fan_2": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanControllers/PSU1_Fan_2",
                        "@odata.type": "#OemManager.FanController",
                        "FFGainCoefficient": 1,
                        "FFOffCoefficient": 0,
                        "ICoefficient": 0,
                        "ILimitMax": 0,
                        "ILimitMin": 0,
                        "Inputs": [
                            "PSU1 Fan Speed 2"
                        ],
                        "NegativeHysteresis": 2,
                        "OutLimitMax": 100,
                        "OutLimitMin": 0,
                        "Outputs": [
                            "Pwm PSU1 Fan 2"
                        ],
                        "PCoefficient": 0,
                        "PositiveHysteresis": 0,
                        "SlewNeg": 0,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/PSU"
                            }
                        ]
                    },
                    "PSU2_Fan_1": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanControllers/PSU2_Fan_1",
                        "@odata.type": "#OemManager.FanController",
                        "FFGainCoefficient": 1,
                        "FFOffCoefficient": 0,
                        "ICoefficient": 0,
                        "ILimitMax": 0,
                        "ILimitMin": 0,
                        "Inputs": [
                            "PSU2 Fan Speed 1"
                        ],
                        "NegativeHysteresis": 2,
                        "OutLimitMax": 100,
                        "OutLimitMin": 0,
                        "Outputs": [
                            "Pwm PSU2 Fan 1"
                        ],
                        "PCoefficient": 0,
                        "PositiveHysteresis": 0,
                        "SlewNeg": 0,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/PSU"
                            }
                        ]
                    },
                    "PSU2_Fan_2": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanControllers/PSU2_Fan_2",
                        "@odata.type": "#OemManager.FanController",
                        "FFGainCoefficient": 1,
                        "FFOffCoefficient": 0,
                        "ICoefficient": 0,
                        "ILimitMax": 0,
                        "ILimitMin": 0,
                        "Inputs": [
                            "PSU2 Fan Speed 2"
                        ],
                        "NegativeHysteresis": 2,
                        "OutLimitMax": 100,
                        "OutLimitMin": 0,
                        "Outputs": [
                            "Pwm PSU2 Fan 2"
                        ],
                        "PCoefficient": 0,
                        "PositiveHysteresis": 0,
                        "SlewNeg": 0,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/PSU"
                            }
                        ]
                    }
                },
                "FanZones": {
                    "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones",
                    "@odata.type": "#OemManager.FanZones",
                    "Left": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Left",
                        "@odata.type": "#OemManager.FanZone",
                        "Chassis": {
                            "@odata.id": "/redfish/v1/Chassis/WC_Baseboard"
                        },
                        "FailSafePercent": 100,
                        "MinThermalOutput": 30
                    },
                    "PSU": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/PSU",
                        "@odata.type": "#OemManager.FanZone",
                        "Chassis": {
                            "@odata.id": "/redfish/v1/Chassis/WC_Baseboard"
                        },
                        "FailSafePercent": 100,
                        "MinThermalOutput": 30
                    },
                    "Right": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Right",
                        "@odata.type": "#OemManager.FanZone",
                        "Chassis": {
                            "@odata.id": "/redfish/v1/Chassis/WC_Baseboard"
                        },
                        "FailSafePercent": 100,
                        "MinThermalOutput": 30
                    }
                },
                "PidControllers": {
                    "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers",
                    "@odata.type": "#OemManager.PidControllers",
                    "BMC_Temp": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers/BMC_Temp",
                        "@odata.type": "#OemManager.PidController",
                        "FFGainCoefficient": 0,
                        "FFOffCoefficient": 0,
                        "ICoefficient": -1,
                        "ILimitMax": 100,
                        "ILimitMin": 30,
                        "Inputs": [
                            "BMC Temp"
                        ],
                        "NegativeHysteresis": 5,
                        "OutLimitMax": 100,
                        "OutLimitMin": 30,
                        "PCoefficient": -0.15,
                        "PositiveHysteresis": 0,
                        "SetPoint": 80,
                        "SlewNeg": -1,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Left"
                            }
                        ]
                    },
                    "CPU1_DIMM_ABCD": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers/CPU1_DIMM_ABCD",
                        "@odata.type": "#OemManager.PidController",
                        "FFGainCoefficient": 0,
                        "FFOffCoefficient": 0,
                        "ICoefficient": -1,
                        "ILimitMax": 100,
                        "ILimitMin": 30,
                        "Inputs": [
                            "DIMM [ABCD]\\d+ CPU1"
                        ],
                        "NegativeHysteresis": 5,
                        "OutLimitMax": 100,
                        "OutLimitMin": 30,
                        "PCoefficient": -0.15,
                        "PositiveHysteresis": 0,
                        "SetPoint": 80,
                        "SlewNeg": -1,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Left"
                            },
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Right"
                            }
                        ]
                    },
                    "CPU1_DIMM_EFGH": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers/CPU1_DIMM_EFGH",
                        "@odata.type": "#OemManager.PidController",
                        "FFGainCoefficient": 0,
                        "FFOffCoefficient": 0,
                        "ICoefficient": -1,
                        "ILimitMax": 100,
                        "ILimitMin": 30,
                        "Inputs": [
                            "DIMM [EFGH]\\d+ CPU1"
                        ],
                        "NegativeHysteresis": 5,
                        "OutLimitMax": 100,
                        "OutLimitMin": 30,
                        "PCoefficient": -0.15,
                        "PositiveHysteresis": 0,
                        "SetPoint": 80,
                        "SlewNeg": -1,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Left"
                            }
                        ]
                    },
                    "CPU2_DIMM_ABCD": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers/CPU2_DIMM_ABCD",
                        "@odata.type": "#OemManager.PidController",
                        "FFGainCoefficient": 0,
                        "FFOffCoefficient": 0,
                        "ICoefficient": -1,
                        "ILimitMax": 100,
                        "ILimitMin": 30,
                        "Inputs": [
                            "DIMM [ABCD]\\d+ CPU2"
                        ],
                        "NegativeHysteresis": 5,
                        "OutLimitMax": 100,
                        "OutLimitMin": 30,
                        "PCoefficient": -0.15,
                        "PositiveHysteresis": 0,
                        "SetPoint": 80,
                        "SlewNeg": -1,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Right"
                            },
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/PSU"
                            }
                        ]
                    },
                    "CPU2_DIMM_EFGH": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers/CPU2_DIMM_EFGH",
                        "@odata.type": "#OemManager.PidController",
                        "FFGainCoefficient": 0,
                        "FFOffCoefficient": 0,
                        "ICoefficient": -1,
                        "ILimitMax": 100,
                        "ILimitMin": 30,
                        "Inputs": [
                            "DIMM [EFGH]\\d+ CPU2"
                        ],
                        "NegativeHysteresis": 5,
                        "OutLimitMax": 100,
                        "OutLimitMin": 30,
                        "PCoefficient": -0.15,
                        "PositiveHysteresis": 0,
                        "SetPoint": 80,
                        "SlewNeg": -1,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Left"
                            },
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Right"
                            }
                        ]
                    },
                    "CPU_1_VR_Temp": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers/CPU_1_VR_Temp",
                        "@odata.type": "#OemManager.PidController",
                        "FFGainCoefficient": 0,
                        "FFOffCoefficient": 0,
                        "ICoefficient": -1,
                        "ILimitMax": 100,
                        "ILimitMin": 30,
                        "Inputs": [
                            "CPU1 VR Mem ABCD Temp",
                            "CPU1 VR Mem ABCD Temp",
                            "CPU1 VR P1V8"
                        ],
                        "NegativeHysteresis": 5,
                        "OutLimitMax": 100,
                        "OutLimitMin": 30,
                        "PCoefficient": -0.15,
                        "PositiveHysteresis": 0,
                        "SetPoint": 85,
                        "SlewNeg": -1,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Left"
                            }
                        ]
                    },
                    "CPU_2_VR_Temp": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers/CPU_2_VR_Temp",
                        "@odata.type": "#OemManager.PidController",
                        "FFGainCoefficient": 0,
                        "FFOffCoefficient": 0,
                        "ICoefficient": -1,
                        "ILimitMax": 100,
                        "ILimitMin": 30,
                        "Inputs": [
                            "CPU2 VR Mem ABCD Temp",
                            "CPU2 VR Mem ABCD Temp",
                            "CPU2 VR P1V8"
                        ],
                        "NegativeHysteresis": 5,
                        "OutLimitMax": 100,
                        "OutLimitMin": 30,
                        "PCoefficient": -0.15,
                        "PositiveHysteresis": 0,
                        "SetPoint": 85,
                        "SlewNeg": -1,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Right"
                            },
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/PSU"
                            }
                        ]
                    },
                    "DTS_CPU1": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers/DTS_CPU1",
                        "@odata.type": "#OemManager.PidController",
                        "FFGainCoefficient": 0,
                        "FFOffCoefficient": 0,
                        "ICoefficient": -0.2,
                        "ILimitMax": 100,
                        "ILimitMin": 30,
                        "Inputs": [
                            "DTS CPU1"
                        ],
                        "NegativeHysteresis": 5,
                        "OutLimitMax": 100,
                        "OutLimitMin": 30,
                        "PCoefficient": -0.1,
                        "PositiveHysteresis": 0,
                        "SetPoint": 75,
                        "SlewNeg": -1,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Left"
                            }
                        ]
                    },
                    "DTS_CPU2": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers/DTS_CPU2",
                        "@odata.type": "#OemManager.PidController",
                        "FFGainCoefficient": 0,
                        "FFOffCoefficient": 0,
                        "ICoefficient": -2,
                        "ILimitMax": 100,
                        "ILimitMin": 30,
                        "Inputs": [
                            "DTS CPU2"
                        ],
                        "NegativeHysteresis": 5,
                        "OutLimitMax": 100,
                        "OutLimitMin": 30,
                        "PCoefficient": -0.1,
                        "PositiveHysteresis": 0,
                        "SetPoint": 75,
                        "SlewNeg": -1,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Right"
                            },
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/PSU"
                            }
                        ]
                    },
                    "Exit_Air_Temp": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers/Exit_Air_Temp",
                        "@odata.type": "#OemManager.PidController",
                        "FFGainCoefficient": 0,
                        "FFOffCoefficient": 0,
                        "ICoefficient": -4.64,
                        "ILimitMax": 100,
                        "ILimitMin": 30,
                        "Inputs": [
                            "Exit Air Temp"
                        ],
                        "NegativeHysteresis": 5,
                        "OutLimitMax": 100,
                        "OutLimitMin": 30,
                        "PCoefficient": -0.15,
                        "PositiveHysteresis": 0,
                        "SetPoint": 75,
                        "SlewNeg": -1,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Left"
                            },
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Right"
                            }
                        ]
                    },
                    "Left_Rear_Board_Temp": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers/Left_Rear_Board_Temp",
                        "@odata.type": "#OemManager.PidController",
                        "FFGainCoefficient": 0,
                        "FFOffCoefficient": 0,
                        "ICoefficient": -1,
                        "ILimitMax": 100,
                        "ILimitMin": 30,
                        "Inputs": [
                            "Left Rear Board Temp"
                        ],
                        "NegativeHysteresis": 5,
                        "OutLimitMax": 100,
                        "OutLimitMin": 30,
                        "PCoefficient": -0.15,
                        "PositiveHysteresis": 0,
                        "SetPoint": 60,
                        "SlewNeg": -1,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Left"
                            },
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Right"
                            }
                        ]
                    },
                    "PSU1_Temperature": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers/PSU1_Temperature",
                        "@odata.type": "#OemManager.PidController",
                        "FFGainCoefficient": 0,
                        "FFOffCoefficient": 0,
                        "ICoefficient": -4.64,
                        "ILimitMax": 100,
                        "ILimitMin": 30,
                        "Inputs": [
                            "PSU1 Temperature"
                        ],
                        "NegativeHysteresis": 5,
                        "OutLimitMax": 100,
                        "OutLimitMin": 30,
                        "PCoefficient": -0.15,
                        "PositiveHysteresis": 0,
                        "SetPoint": 50,
                        "SlewNeg": -1,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/PSU"
                            }
                        ]
                    },
                    "PSU2_Temperature": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers/PSU2_Temperature",
                        "@odata.type": "#OemManager.PidController",
                        "FFGainCoefficient": 0,
                        "FFOffCoefficient": 0,
                        "ICoefficient": -4.64,
                        "ILimitMax": 100,
                        "ILimitMin": 30,
                        "Inputs": [
                            "PSU2 Temperature"
                        ],
                        "NegativeHysteresis": 5,
                        "OutLimitMax": 100,
                        "OutLimitMin": 30,
                        "PCoefficient": -0.15,
                        "PositiveHysteresis": 0,
                        "SetPoint": 50,
                        "SlewNeg": -1,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/PSU"
                            }
                        ]
                    },
                    "Right_Rear_Board_Temp": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers/Right_Rear_Board_Temp",
                        "@odata.type": "#OemManager.PidController",
                        "FFGainCoefficient": 0,
                        "FFOffCoefficient": 0,
                        "ICoefficient": -1,
                        "ILimitMax": 100,
                        "ILimitMin": 30,
                        "Inputs": [
                            "Right Rear Board Temp"
                        ],
                        "NegativeHysteresis": 5,
                        "OutLimitMax": 100,
                        "OutLimitMin": 30,
                        "PCoefficient": -0.15,
                        "PositiveHysteresis": 0,
                        "SetPoint": 60,
                        "SlewNeg": -1,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Left"
                            }
                        ]
                    },
                    "SSB_Temp": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/PidControllers/SSB_Temp",
                        "@odata.type": "#OemManager.PidController",
                        "FFGainCoefficient": 0,
                        "FFOffCoefficient": 0,
                        "ICoefficient": -1,
                        "ILimitMax": 100,
                        "ILimitMin": 30,
                        "Inputs": [
                            "SSB Temp"
                        ],
                        "NegativeHysteresis": 5,
                        "OutLimitMax": 100,
                        "OutLimitMin": 30,
                        "PCoefficient": -0.15,
                        "PositiveHysteresis": 0,
                        "SetPoint": 75,
                        "SlewNeg": -1,
                        "SlewPos": 0,
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Left"
                            },
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Right"
                            }
                        ]
                    }
                },
                "Profile": "Performance",
                "Profile@Redfish.AllowableValues": [
                    "Acoustic",
                    "Performance"
                ],
                "StepwiseControllers": {
                    "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/StepwiseControllers",
                    "@odata.type": "#OemManager.StepwiseControllers",
                    "Front_Panel_LCC": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/StepwiseControllers/Front_Panel_LCC",
                        "@odata.type": "#OemManager.StepwiseController",
                        "Direction": "Floor",
                        "Inputs": [
                            "Front Panel Temp"
                        ],
                        "NegativeHysteresis": 2,
                        "PositiveHysteresis": 0,
                        "Steps": [
                            {
                                "Output": 50,
                                "Target": 20
                            },
                            {
                                "Output": 60,
                                "Target": 30
                            }
                        ],
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Left"
                            },
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/Right"
                            }
                        ]
                    },
                    "PSU1_LCC": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/StepwiseControllers/PSU1_LCC",
                        "@odata.type": "#OemManager.StepwiseController",
                        "Direction": "Floor",
                        "Inputs": [
                            "PSU1 Temperature"
                        ],
                        "NegativeHysteresis": 2,
                        "PositiveHysteresis": 0,
                        "Steps": [
                            {
                                "Output": 40,
                                "Target": 30
                            },
                            {
                                "Output": 100,
                                "Target": 65
                            }
                        ],
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/PSU"
                            }
                        ]
                    },
                    "PSU2_LCC": {
                        "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/StepwiseControllers/PSU2_LCC",
                        "@odata.type": "#OemManager.StepwiseController",
                        "Direction": "Floor",
                        "Inputs": [
                            "PSU2 Temperature"
                        ],
                        "NegativeHysteresis": 2,
                        "PositiveHysteresis": 0,
                        "Steps": [
                            {
                                "Output": 40,
                                "Target": 30
                            },
                            {
                                "Output": 100,
                                "Target": 65
                            }
                        ],
                        "Zones": [
                            {
                                "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc/Fan/FanZones/PSU"
                            }
                        ]
                    }
                }
            }
        }
    },
    "PowerState": "On",
    "SerialConsole": {
        "ConnectTypesSupported": [
            "IPMI",
            "SSH"
        ],
        "MaxConcurrentSessions": 15,
        "ServiceEnabled": true
    },
    "ServiceEntryPointUUID": "05d4970e-c17a-5fc6-9583-879c13ce9a4e",
    "Status": {
        "Health": "Warning",
        "HealthRollup": "Warning",
        "State": "Enabled"
    },
    "UUID": "5dbc0ca3-adc3-451b-a9a3-53a5cf2cc29f",
    "VirtualMedia": {
        "@odata.id": "/redfish/v1/Managers/bmc/VirtualMedia"
    }
}

**Comment by kuiyingw** [comment]
Issue is fixed. Please wait patch is published. I0af884927c6d58bc0710d0f75c424213a5a3d5e2

**Comment by leiyu-bytedance** [comment]
@kuiyingw The issue remains on d81f2708c4462a62e3b5e8d08643eb2b8895dde7
The change id `I0af884927c6d58bc0710d0f75c424213a5a3d5e2` is not found on gerrit, is it possible to publish it so that I could cherry-pick it?

**Comment by leiyu-bytedance** [comment]
The issue is gone on the updated intel branch (c16fb8893)
